# Basic
title: 激情为梦想而生
subtitle: 传递正能量
welcome_message: I would like to collect a little happy, by the time the transfer of the accumulation of large energy, through the temperature of the fingers, expected years static good.
description: 我愿收藏点滴的快乐，经流年的流转积累大大的能量，透过手指的温度，期许岁月静好。
creator: <a href="http://onev.cat">@onevcat</a>

url: "http://blog.tryingx.com"

permalink: /:year/:month/:title/

# Format
highlighter: plain

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo:

# Social
social:
    weibo: onevcat
    github: onevcat
    twitter: onevcat
    gplus: 107108267983477358170
    mail: onev@onevcat.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
